import { Produk, Kategori } from '@/types';

export const MOCK_CATEGORIES: Kategori[] = [
  { id: 'cat-wisuda', nama: 'Buket Wisuda', created_at: '2026-01-01' },
  { id: 'cat-anniversary', nama: 'Buket Anniversary', created_at: '2026-01-01' },
  { id: 'cat-bunga-segar', nama: 'Bunga Segar', created_at: '2026-01-01' },
  { id: 'cat-snack', nama: 'Buket Snack', created_at: '2026-01-01' },
  { id: 'cat-uang-boneka', nama: 'Uang & Boneka', created_at: '2026-01-01' },
];

export const MOCK_PRODUCTS: Produk[] = [
  {
    id: 'prod-1',
    nama: 'Buket Wisuda Elegant Rose & Teddy',
    slug: 'buket-wisuda-elegant-rose-teddy',
    kategori_id: 'cat-wisuda',
    harga: 185000,
    deskripsi: 'Buket wisuda spesial dilengkapi boneka toga mini, mawar artifisial premium bernuansa pink soft, dan pita satin elegan. Termasuk selempang nama dan kartu ucapan kustom.',
    foto_url: 'https://images.unsplash.com/photo-1523693916903-027d144a2806?w=600&q=80',
    status: 'tersedia',
    created_at: '2026-01-01',
    kategori: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-2',
    nama: 'Buket Anniversary Pastel Peony Romance',
    slug: 'buket-anniversary-pastel-peony-romance',
    kategori_id: 'cat-anniversary',
    harga: 250000,
    deskripsi: 'Rangkaian romantis bunga peony dan mawar pastel segar dengan aroma wangi lembut. Hadiah sempurna untuk merayakan momen berharga bersama pasangan.',
    foto_url: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=600&q=80',
    status: 'po',
    created_at: '2026-01-02',
    kategori: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-3',
    nama: 'Buket Mawar Merah Classic Velvet',
    slug: 'buket-mawar-merah-classic-velvet',
    kategori_id: 'cat-bunga-segar',
    harga: 175000,
    deskripsi: '10 tangkai mawar merah segar pilihan dengan pembungkus hitam doff & pita mint. Simbol cinta abadi yang tak pernah salah.',
    foto_url: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80',
    status: 'tersedia',
    created_at: '2026-01-03',
    kategori: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-4',
    nama: 'Buket Snack Cokelat Ferrero & Pocky',
    slug: 'buket-snack-cokelat-ferrero-pocky',
    kategori_id: 'cat-snack',
    harga: 120000,
    deskripsi: 'Buket manis berisi cokelat premium Ferrero Rocher, Pocky, dan aneka snack favorit berhiaskan baby breath kering. Pas untuk ulang tahun & hadiah santai.',
    foto_url: 'https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?w=600&q=80',
    status: 'tersedia',
    created_at: '2026-01-04',
    kategori: MOCK_CATEGORIES[3],
  },
  {
    id: 'prod-5',
    nama: 'Buket Uang Kipas Aesthetic (10 Lembar)',
    slug: 'buket-uang-kipas-aesthetic',
    kategori_id: 'cat-uang-boneka',
    harga: 95000,
    deskripsi: 'Rangkaian buket uang berbentuk kipas elegan (harga belum termasuk nominal uang lembaran). Dilapisi plastik pelindung uang agar tidak rusak.',
    foto_url: 'https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600&q=80',
    status: 'tersedia',
    created_at: '2026-01-05',
    kategori: MOCK_CATEGORIES[4],
  },
  {
    id: 'prod-6',
    nama: 'Buket Wisuda Sunflower Golden Spirit',
    slug: 'buket-wisuda-sunflower-golden-spirit',
    kategori_id: 'cat-wisuda',
    harga: 160000,
    deskripsi: 'Bunga matahari segar melambangkan masa depan cerah, dipadukan bunga aster putih dan wrapping nuansa beige aesthetic.',
    foto_url: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=600&q=80',
    status: 'tersedia',
    created_at: '2026-01-06',
    kategori: MOCK_CATEGORIES[0],
  },
];
